language: generic

python:
  - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install python3 mpich2 gfortran

install: 
  - pip install --user sphinx sphinx_rtd_theme

script: bash ./build_and_deploy.sh

env:
  global:
  - COMMIT_AUTHOR_EMAIL: "atmyers@lbl.gov"

addons:
  apt:
    packages:
      - doxygen
